name: Backend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: cd api && npm install --legacy-peer-deps

    - name: Set up environment variables
      run: |
        echo "PORT=${{ secrets.PORT }}" >> $GITHUB_ENV
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> $GITHUB_ENV
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV

    - name: Run backend tests
      run: cd api && npm test
